### ISSUE TITLE
PDF assets seem to not work in Assets Catalog 

### ISSUE THREAD

**Issue by hepspl** [skiptools/skip-ui#32]
One of the formats supported by Assets Catalog is PDF.
This is a very good way of putting vector images so Xcode will automatically prepare rasterized (or preserve vector) images for various screens densities at build time.

However it seems that SKIP is not handling PDFs well (even if xcode is rasterizing them).
I am unable to see any image supplied in PDF format rendered on Android app (iOS works ok).

I hope you would address this issue as I find this crucial when working with images in apps.

**Comment by marcprux** [comment]
I've gone ahead and implemented this in skip-ui 0.9.4. You can now put PDFs in the asset catalog for the top-level module, and you will be able to load it by name. Be sure to use the `Image(name, bundle: .module)` syntax, since the asset catalog needs to be added to the top-level SwiftPM Resources/ folder so it can be handled by the Skip transpiler.

If you mark the PDF asset with "Preserve Vector Data", it will use the `foregroundStyle` to tint the image, just like on iOS. Otherwise, the colors in the PDF will be used.

You can get the latest version with `File`/`Packages`/`Upgrade to Latest Package Versions`. Please let us know if you run into any issues with this new feature.

<img width="1920" alt="Screenshot 2024-05-29 at 11 58 54" src="https://github.com/skiptools/skip-ui/assets/659086/c1fbef7f-7d91-40d4-ae0c-78ee534731e1">

**Comment by hepspl** [comment]
How awesome! It works! Thank you for this!

However I don't see any difference between "Preserve Vector Data" enabled or disabled.
Each time I can see on Android that image is rastered and using original colors.

**Comment by marcprux** [comment]
> However I don't see any difference between "Preserve Vector Data" enabled or disabled.

The colors are actually supported using the "Render As" asset setting. "Template Image" will allow you to set the foregroundStyle.
